- hosts: your-host
  gather_facts: no
  become: yes
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_sudo_pass: "{{ ANSIBLE_SUDO_PASS }}"

  tasks:
    - name: Install dependencies
      ansible.builtin.package:
        name: restic
        state: latest
    
    - name: Install kumonoboru
      ansible.builtin.copy:
        src: kumonoboru.sh
        dest: /usr/local/bin/kumonoboru.sh
        mode: 'a+x'

    - name: Template service and timer to host
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: /etc/systemd/system/{{ item }}
      with_items:
        - kumonoboru.service
        - kumonoboru.timer
        - kumonoboru-prune.service
        - kumonoboru-prune.timer

    - name: Start kumonoboru timer
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        daemon_reload: true
      with_items:
        - kumonoboru.timer
        - kumonoboru-prune.timer
